# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 16

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
padding = { x = 8, y = 8 }
dynamic_padding = true

[mouse]
hide_when_typing = true
