# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]


[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 16

[window]
decorations = "Buttonless"
padding = {x =2, y=2}
