# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular"}
size = 16

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
padding = { x = 8, y = 8 }
dynamic_padding = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Tab", mods = "Control", chars = "\u0002n"}, # cycle tmux window
  { key = "Tab", mods = "Control|Shift", chars = "\u0002p"}, # cycle tmux window, backwards
  { key = "t", mods = "Control", chars = "\u0002c"}, # new tmux window
  { key = "w", mods = "Control", chars = "\u0002&"}, # close tmux pane/window
  { key = "f", mods = "Control", chars = "\u0002z"}, # zoom tmux pane
  { key = "h", mods = "Control", chars = "\u0002\u001b[D"}, # navigate to pane, left
  { key = "j", mods = "Control", chars = "\u0002\u001b[B"}, # navigate to pane, down
  { key = "k", mods = "Control", chars = "\u0002\u001b[A"}, # navigate to pane, up
  { key = "l", mods = "Control", chars = "\u0002\u001b[C"}, # navigate to pane, right
]
