#  https://github.com/joshmedeski/sesh

blacklist = [
    "scratch",
]

[default_session]
startup_command = "vim -c 'Oil'" # open vim with file manager
preview_command = "eza --oneline --all --icons=always --color=always {}"
startup_command_ignore_dirs = ["~/"]
