#  https://github.com/joshmedeski/sesh

blacklist = [
    "scratch",
    "template",
    "hello go",
    "dotfiles",
    "black and white",
]

[default_session]
startup_command = "vim" 
preview_command = "ls -la"
startup_command_ignore_dirs = ["~/"]

# configs

# [[session]]
# name = "nvim config"
# path = "~/.dotfiles/nvim"
# startup_command = "vim -c ':Telescope find_files'"
#
# [[session]]
# name = "sesh config"
# path = "~/.dotfiles/"
# startup_command = "vim sesh/sesh.toml"
# preview_command = "cat ~/.dotfiles/sesh/sesh.toml"
#
# [[session]]
# name = "tmux config"
# path = "~/.dotfiles/"
# startup_command = "vim tmux/tmux.conf"
# preview_command = "bat --color=always ~/.dotfiles/tmux/tmux.conf"
#
#
# [[session]]
# name = "zsh config"
# path = "~/.dotfiles/"
# startup_command = "vim zsh/.zshrc"
#
# [[session]]
# name = "alacritty config"
# path = "~/.dotfiles/"
# startup_command = "vim alacritty/alacritty.toml"
#
# [[session]]
# name = "lazygit config"
# path = "~/.dotfiles/"
# startup_command = "vim lazygit/config.yml"
#
# [[session]]
# name = "yazi config"
# path = "~/.dotfiles/"
# startup_command = "vim yazi/yazi.toml"
