#  ███████╗███████╗███████╗██╗  ██╗     ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
#  ██╔════╝██╔════╝██╔════╝██║  ██║    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
#  ███████╗█████╗  ███████╗███████║    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ╚════██║██╔══╝  ╚════██║██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ███████║███████╗███████║██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
#  Smart session manager for the terminal
#  https://github.com/joshmedeski/sesh

# [default_session]
# startup_command = "vim -c ':Telescope find_files'"
# startup_command_ignore_dirs = ["~/"]

# configs

[[session]]
name = "nvim config"
path = "~/.dotfiles/nvim"
startup_command = "vim -c ':Telescope find_files'"

[[session]]
name = "sesh config"
path = "~/.dotfiles/"
startup_command = "vim sesh/sesh.toml"

[[session]]
name = "tmux config"
path = "~/.dotfiles/"
startup_command = "vim tmux/tmux.conf"

[[session]]
name = "zsh config"
path = "~/.dotfiles/"
startup_command = "vim zsh/.zshrc"

[[session]]
name = "alacritty config"
path = "~/.dotfiles/"
startup_command = "vim alacritty/alacritty.toml"

[[session]]
name = "lazygit config"
path = "~/.dotfiles/"
startup_command = "vim lazygit/config.yml"

[[session]]
name = "yazi config"
path = "~/.dotfiles/"
startup_command = "vim yazi/yazi.toml"
