#  https://github.com/joshmedeski/sesh

blacklist = [
    "scratch",
]

sort_order = [
    "tmuxinator", # shown first
    "config",
    "tmux",
    "zoxide",
]

[default_session]
startup_command = "vim +Oil" # open vim with file manager
preview_command = "eza --oneline --all --icons=always --color=always {}"
startup_command_ignore_dirs = ["~/"]
